FEATURE_COLUMNS = [
    "fuzzy_score",
    "ordinary_ratio",
    "token_sort_ratio",
    "character_length_ratio",
    "token_count_ratio",
    "same_category",
    "identity_tokens_both_present",
    "shared_identity_token",
    "identity_token_overlap_ratio",
    "identity_token_mismatch",

    "luxury_variant_mismatch",
    "overwater_mismatch",

    "bedroom_count_both_known",
    "same_bedroom_count",
    "room_class_both_known",
    "same_room_class",
    "view_both_known",
    "same_view",
    "bed_type_both_known",
    "same_bed_type",
    "bed_type_compatible",
    "bed_config_both_present",
    "same_bed_configuration",
    "occupancy_both_known",
    "same_occupancy",
    "both_single_use",
    "single_use_mismatch",
    "both_balcony",
    "balcony_mismatch",
    "both_pool_access",
    "pool_access_mismatch",
    "both_swim_up",
    "swim_up_mismatch",
]